[language-server]
racket = { command = "racket", args = ["-l", "racket-langserver"] }

[[language]]
name = "racket"
scope = "source.racket"
file-types = ["rkt", "rktd", "rktl", "scrbl", "zuo"]
shebangs = ["racket", "zuo"]
comment-token = ";"
indent = { tab-width = 2, unit = "  " }
block-comment-tokens = { start = "#|", end = "|#" }
language-servers = [ "racket" ]
grammar = "scheme"
